apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace:
  name:
  labels:
    key: value
  annotations:
    key: value
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
