apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: 
  labels:
    app: 
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: 
subjects:
  - kind: ServiceAccount
    name: 

