apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cloud-shell
  labels:
    app: cloud-shell
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cloud-shell
subjects:
  - kind: ServiceAccount
    name: cloud-shell